# KNN on IRIS DATASET

#### By Muhammad Arham
#### 1001686912

In [150]:
#IMPORTS

import pandas as pd
import numpy as np
import math
import operator
from collections import Counter
import scipy

### Importing the IRIS DATASET

In [151]:
col=['sepal_length','sepal_width','petal_length','petal_width','class']
data=pd.read_csv("iris.data", header = None, names = col )

In [152]:
data.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [153]:
 from sklearn.model_selection import train_test_split

### Splitting data into development and test set

In [197]:
x=iris.iloc[:,:4]
y=iris["class"]

# 80/20 split of dataset
x_develop,x_test,y_develop,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
# converting dataframe into numpy arrays for easier iteration later on
x_develop,x_test,y_develop,y_test = np.array(x_develop),np.array(x_test),np.array(y_develop),np.array(y_test)

## KNN Algorithm

#### Euclidean Distance

In [173]:
def euclidean_distance(row1, row2):
    distance = 0.0
    for i in range(len(row1)-1):
        distance += (row1[i] - row2[i])**2
        ##distance += scipy.spatial.distance.euclidean(row1,row2)
    return math.sqrt(distance)


#### Cosine Similarity

In [174]:
def cosine_similarity(row1, row2):
    sim = 0.0
    sim = np.inner(row1, row2) / (norm(row1) * norm(row2))
    return sim

#### Normalized Euclidean Distance

In [175]:
def normalized_euclidean_distance(row1, row2):
    distance = 0.0
    distance = 0.5*(np.std(row1-row2)**2) / (np.std(row1)**2+np.std(row2)**2)
    return distance


### Calculating distances

In [198]:
###Calculating Distances between test and development set rows
## using above mentioned distance metrics

rows = x_test.shape[0]
columns = x_develop.shape[0]

##initializing arrays of array
Edistance = np.zeros((x_test.shape[0],x_develop.shape[0]))
Cdistance = np.zeros((x_test.shape[0],x_develop.shape[0]))
NEdistance = np.zeros((x_test.shape[0],x_develop.shape[0]))


for row in range(rows):
    for col in range(columns):
        #for euclidean
        Edistance[row,col] = euclidean_distance(x_test[row], x_develop[col])
        #for cosine similarity
        Cdistance[row,col] = cosine_similarity(x_test[row], x_develop[col])
        #for normalized euclidean distance
        NEdistance[row,col] = normalized_euclidean_distance(x_test[row], x_develop[col])

print (Edistance)#Euclidean distance
print (Cdistance)#Cosine Similarity
print (NEdistance)#Normalized Euclidean distance

[[4.07185461 3.6        0.73484692 ... 3.71214224 0.78740079 1.57480157]
 [1.3190906  0.63245553 2.96310648 ... 0.54772256 2.596151   4.49888875]
 [6.73943618 6.03324125 2.73861279 ... 6.16927873 3.46698716 1.2328828 ]
 ...
 [5.3860932  4.69148164 1.50665192 ... 4.87134478 2.22934968 0.36055513]
 [0.74833148 1.6673332  3.55246393 ... 1.42828569 2.81424946 5.05371151]
 [0.80622577 1.58429795 3.38378486 ... 1.40356688 2.64764046 4.87749936]]
[[0.87730887 0.89539169 0.99723763 ... 0.88600082 0.99870624 0.99654908]
 [0.99449144 0.99693372 0.94073609 ... 0.99700311 0.93245912 0.89123068]
 [0.80624005 0.82899538 0.98170628 ... 0.81816902 0.98594058 0.99718842]
 ...
 [0.84361412 0.86488867 0.98933363 ... 0.85077925 0.99169396 0.99918424]
 [0.99188736 0.99468916 0.94492558 ... 0.99603721 0.93684057 0.89626141]
 [0.99076917 0.99419158 0.94955818 ... 0.99411692 0.94211471 0.90292976]]
[[0.19133507 0.18142145 0.00729167 ... 0.17182847 0.00511408 0.00928881]
 [0.01082143 0.00494908 0.0909198  ... 

### Prediction based on distances

In [208]:
rows = Edistance.shape[0]

k = 9

#generates empty arrays with rows equal to number of test rows
#E_pred = np.zeros(rows)
#C_pred = np.zeros(rows)
#NE_pred = np.zeros(rows)
E_pred = []
#E_pred = np.array(E_pred)

for i in range(rows):
    #print(NEdistance[i,:])
    E_y_indexes = np.argsort(Edistance[i,:])
    print(Edistance[i][E_y_indexes])
    #print(E_y_indexes)
    #C_y_indexes = np.argsort(Cdistance[i,:])
    #NE_y_indexes = np.argsort(NEdistance[i,:])
    #print('HELO',Edistance[77])
    closest = E_y_indexes[:k]
    closest_y = y_develop[E_y_indexes[:k]]
    value = Counter(closest_y).most_common()
    print(closest)
    print(closest_y)
    print(value[0][0])
    E_pred.append(value[0][0])
    #E_pred  = np.argmax(np.bincount(closest_y))


#print(E_pred)
#print(closest_y)    
num_correct = np.sum(E_pred == y_test)
accuracy = float(num_correct)/y_test.shape[0]

print('Correctly classified instances',num_correct)
print('Incorrectly classified instances', len(E_pred)-num_correct)
print("Accuracy based on Euclidean Distance with 7 Neighbors",accuracy)

[0.1        0.14142136 0.2236068  0.24494897 0.3        0.41231056
 0.41231056 0.42426407 0.42426407 0.4472136  0.45825757 0.46904158
 0.48989795 0.5        0.50990195 0.50990195 0.50990195 0.51961524
 0.53851648 0.53851648 0.57445626 0.57445626 0.58309519 0.6164414
 0.6164414  0.64031242 0.64807407 0.67082039 0.67082039 0.67082039
 0.678233   0.678233   0.678233   0.7        0.7        0.7
 0.71414284 0.72111026 0.73484692 0.75498344 0.78102497 0.78740079
 0.80622577 0.87749644 0.90553851 0.91651514 0.92195445 0.92736185
 0.92736185 0.92736185 0.96953597 0.98488578 1.04880885 1.08166538
 1.1        1.1045361  1.12249722 1.15325626 1.2083046  1.2328828
 1.25299641 1.26885775 1.26885775 1.28062485 1.34164079 1.40712473
 1.56843871 1.57480157 1.74928557 1.81383571 1.8493242  1.88679623
 1.91049732 1.95192213 1.99499373 2.00249844 2.13541565 2.42899156
 2.56124969 2.74954542 3.13687743 3.13847097 3.14483704 3.20156212
 3.27108545 3.29545141 3.36303434 3.39705755 3.39705755 3.40587727
 3.4

In [188]:
print(y_test)

['Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor']
